### ISSUE TITLE
'redux-webmidi' is not in the npm registry.

### ISSUE THREAD

**Issue by Carnewal** [plus1tv/redux-webmidi#1]
I'm getting 

> Registry returned 404 for GET on https://registry.npmjs.org/redux-webmidi  

Please add redux-webmidi to the npm registry.

**Comment by kennetpostigo** [comment]
@Carnewal hey, thanks for your interest in this repo. @alaingalvan will cut a release for this.

**Comment by alaingalvan** [comment]
@Carnewal - I'll be releasing it on NPM later in the evening. (So about 10 hours from now.) ⏲

**Comment by alaingalvan** [comment]
@Carnewal - alrighty, published and tested.
